package com.magicrecoder.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.magicrecoder.recoderapp.RecorderInfo;

import com.magicrecoder.greendao.RecorderInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recorderInfoDaoConfig;

    private final RecorderInfoDao recorderInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recorderInfoDaoConfig = daoConfigMap.get(RecorderInfoDao.class).clone();
        recorderInfoDaoConfig.initIdentityScope(type);

        recorderInfoDao = new RecorderInfoDao(recorderInfoDaoConfig, this);

        registerDao(RecorderInfo.class, recorderInfoDao);
    }
    
    public void clear() {
        recorderInfoDaoConfig.clearIdentityScope();
    }

    public RecorderInfoDao getRecorderInfoDao() {
        return recorderInfoDao;
    }

}
